<?php
class RbidConfig {
	public $select_winner_automatic = '0';
	public $auctiontype_enable = '1';
	public $auctiontype_val = '2';
	public $auctionpublish_enable = '1';
	public $auctionpublish_val = '0';
	public $date_format = 'Y-m-d';
	public $date_time_format = 'h:iA';
	public $nr_items_per_page = '10';
	public $inner_categories = '1';
	public $enable_countdown = '0';
	public $availability = '3';
	public $archive = '3';
	public $max_nr_tags = '5';
	public $allow_messages = '1';
	public $allow_guest_messaging = '0';
	public $enable_captcha = '1';
	public $hide_contact = '1';
	public $nda_option = '0';
	public $nda_compulsory = '0';
	public $nda_extensions = 'txt,doc,pdf';
	public $enable_attach = '1';
	public $attach_compulsory = '0';
	public $attach_max_size = '1024';
	public $attach_extensions = 'zip,rar,txt, doc, jpg, jpeg, pdf';
	public $workflow = 'quick';
	public $disable_images = '0';
	public $max_picture_size = '2048';
	public $maxnr_images = '3';
	public $main_picture_require = '0';
	public $gallery = 'scrollgallery';
	public $thumb_width = '150';
	public $thumb_height = '150';
	public $medium_width = '500';
	public $medium_height = '500';
	public $bidder_groups = array("0" => "2", "1" => "9", "2" => "8");
	public $seller_groups = array("0" => "2", "1" => "3", "2" => "4", "3" => "5", "4" => "8");
	public $google_key = 'AIzaSyAo5UuNbl70rePmOW_TkrT0ijlgD3OZILI';
	public $googlemap_defx = '33.500178228513306';
	public $googlemap_defy = '-86.81121838671874';
	public $googlemap_default_zoom = '10';
	public $googlemap_distance = '0';
	public $googlemap_unit_available = '5,25,60,100,150, 250, 500';
	public $googlemap_gx = '550';
	public $googlemap_gy = '450';
	public $googlemap_allowed_maps = array("0" => "Map", "1" => "Hybrid");
	public $recaptcha_public_key = '';
	public $recaptcha_private_key = '';
	public $recaptcha_theme = 'red';
	public $choose_antispam_bot = 'joomla';
	public $mailcaptcha_public_key = '';
	public $mailcaptcha_private_key = '';
	public $terms_and_conditions = '<p> </p>
<p class="MsoNormal" style="text-align: center;" align="center">ZAMBOOKI USER AGREEMENT</p>
<p class="MsoNormal" style="text-align: center;" align="center"> </p>
<p class="MsoNormal" style="text-align: center;" align="center">Last Update: July 17, 2011</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">IF YOU DO NOT AGREE TO ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT, YOU MUST NOT USE THE WEBSITE.  BY USING THE WEBSITE, YOU ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTOOD THE TERMS AND CONDITIONS OF THIS AGREEMENT AND YOU AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">This User Agreement (“Agreement”) governs the use of www.Zambooki.com (“Website”), including without limitation participation in its bulletin boards, forums, chats, and all other areas (except to the extent stated otherwise on a specific page) as provided by Zambooki, LLC (“Zambooki,” “We,” or “Our”).  All users of the Website, other than those professionals and contractors seeking to provide services (collectively, “Contractors”) to users of the Website are referred to in this Agreement as “User” or “Users.”</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">Please read the rules contained in this Agreement carefully.  You can access this Agreement any time at http://www.Zambooki.com/useragreement.  Your use of and/or registration on any aspect of the Website will constitute your agreement to comply with these rules.  If you cannot agree with these rules, please do not use the Website.  As a result of your agreement to this Agreement, Zambooki agrees to provide you with information and other computer services subject to the terms and conditions of this Agreement.  You agree to use the Website and the corresponding services in accordance with this Agreement, our Privacy Policy, and any additional terms and conditions that may apply to specific sections of the Website or to products and services available through the Website.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">In addition to reviewing this Agreement, please read Our Privacy Policy.  As stated above, your use of the Website constitutes agreement to its terms and conditions as well.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">The Agreement may be modified from time to time by Zambooki, in its sole discretion and without prior notice.  The date of the most recent revision will appear on this page, so check back often.  Continued access of the Website by a User will constitute your acceptance of any changes or revisions to the Agreement.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">A User’s failure to follow these rules, whether listed below or in bulletins posted at various points in the Website, may result in suspension or termination of that User’s access to the Website, without notice, in addition to Zambooki’s other remedies.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">MONITORING</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">Zambooki strives to provide Users with access to information from Contractors regarding various services provided by those Contractors.  We desire an enjoyable online experience for all of Our Users.  For that reason, We may monitor activity on the Website, including in the bulletin boards, forums, and chats, to foster compliance with this Agreement.  All users of the Website hereby specifically agree to such monitoring.  Nevertheless, We do not make any warranties or guarantees that: (1) the Website, or any portion thereof, will be monitored for accuracy or unacceptable use, (2) apparent statements of fact will be authenticated, or (3) We will take any specific action (or any action at all) in the event of a dispute regarding compliance or non-compliance with this Agreement.  Furthermore, Zambooki expressly makes no representation or warranty as to the accuracy of any information provided to Users from Contractors or information posted by other Users.  Zambooki merely acts as a conduit for information and is not responsible or liable in any respect for the information provided.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">REGISTRATION AND ACCOUNT CREATION</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">Zambooki may at times require that you register and/or set up an account to use certain portions of the Website, or the Website as a whole.  In order to do so, you may be provided, or required to choose, a password, User ID, and/or other registration information (collectively, “Registration Information”).  You agree and represent that all Registration Information provided by you is accurate and up-to-date.  You may not impersonate, imitate, or pretend to be somebody else when registering and/or setting up an account on the Website.  If any of your Registration Information changes, you must update it by using the appropriate update mechanism on the Website, if available.  Otherwise, contact Our Privacy Policy Coordinator as described in Our Privacy Policy.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">USE OF USER ID/PASSWORD</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">If you register and/or set up an account on the Website, you will be solely responsible for maintaining the confidentiality of your Registration Information.  You may not authorize others to use your Registration Information.  You may not sub-license, transfer, sell, or assign your Registration Information and/or this Agreement to any third party without Our written approval.  Any attempt to do so will be null and void and shall be considered a material breach of this Agreement.   Zambooki may assign its rights under this Agreement at any time.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">You are solely responsible for all usage or activity on your account including, but not limited to, use of the account by any person who uses your Registration Information, with or without authorization, or who has access to any computer on which your account resides or is accessible.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">If you have reason to believe that your account is no longer secure (for example, in the event of a loss, theft, or unauthorized disclosure or use of your Registration Information or any credit, debit, or charge card number stored on the Website), you must promptly change the affected Registration Information by using the appropriate update mechanism on the Website, if available, or notify Our Privacy Policy Coordinator as described in Our Privacy Policy.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">FEES AND PAYMENTS</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">Zambooki or third parties may charge you fees for products or services offered for sale through the Website, and/or for access to portions of the Website or the Website as a whole.  You agree to pay all fees and charges, including applicable taxes, incurred through your account at the rates in effect for the billing period in which such fees and charges are incurred, including but not limited to charges for any products or services offered for sale through the Website by Zambooki or by any third party vendor or provider (such fees, charges, and taxes shall collectively be referred to as “Fees”).  Zambooki reserves the right to change the amount of, or basis for determining, any Fees, and to institute new Fees, in its sole discretion and effective upon notice published on the Website.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">If you submit your credit, debit, or charge card information to Zambooki upon registration or otherwise, you give Zambooki permission to charge all Fees incurred through your account to the credit, debit, or charge card you designate.  Any additional Fees (other than renewal fees) will be charged at the time they are incurred.  If payment cannot be charged to your credit, debit, or charge card or your payment is returned to Zambooki for any reason, including charge back, Zambooki reserves the right to either suspend or terminate your account and all its obligations under this Agreement.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">RULES OF USAGE:</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">A.    The Website is not intended for Users under the age of 13, and Zambooki does not knowingly collect personally identifiable information from Users under the age of 13.  Such Users are expressly prohibited from submitting their personally identifiable information to us, and from using portions of the Website for which registration is required, such as Our forums and chat areas.  Any information submitted by such Users will not knowingly be used, posted, or retained by us.</p>
<p class="MsoNormal">B.    Unless otherwise specified, the Website is intended for your personal use only.  You may not authorize others to use the Website, and you are responsible for all use of the Website by you and by those you allow to use, or provide access to, the Website.  You may not impersonate, imitate, or pretend to be somebody else when using the Website.</p>
<p class="MsoNormal">C.    You may not provide to or post on or through the Website any graphics, text, photographs, images, video, audio, or other material that constitutes junk mail, spam, advertising, and/or commercial offers.  You may not repeat the same posting multiple times in a day or week.</p>
<p class="MsoNormal">D.    You agree not to use any obscene, indecent, or offensive language or to provide to or post on or through the Website any graphics, text, photographs, images, video, audio, or other material that is defamatory, abusive, bullying, harassing, racist, hateful, or violent.  You agree to refrain from ethnic slurs, religious intolerance, and personal attacks when using the Website.</p>
<p class="MsoNormal">E.    You further agree not to use any sexually explicit language or to provide to or post on or through the Website any graphics, text, photographs, images, video, audio, or other material that is sexually explicit.  Do not “cyber” or solicit another to “cyber” (participate in virtual sex) on or through the Website.</p>
<p class="MsoNormal">F.    You may not provide to or post on or through the Website any graphics, text, photographs, images, video, audio, or other material that is encrypted, invades anyone’s privacy, or illustrates, references, or encourages conduct that would constitute a criminal offense, give rise to civil liability, or that otherwise violates any local, state, federal, national, or international law or regulation (e.g., drug use, underage drinking).  You agree to use the Website only for lawful purposes and you acknowledge that your failure to do so may subject you to civil and criminal liability.  Do not provide to or post on or through the Website any graphics, text, photographs, images, video, audio, or other material that includes instructions for weapon and/or explosive manufacture or use.</p>
<p class="MsoNormal">G.    You are responsible for ensuring that any graphics, text, photographs, images, video, audio, or other material you provide to or post on the Website, including without limitation in bulletin boards, forums, chats, or elsewhere, does not violate the copyright, trademark, trade secret, or any other personal or proprietary rights of any third party or is provided or posted with the permission of the owner(s) of such rights.</p>
<p class="MsoNormal">H.   The Website may contain graphics, text, photographs, images, video, audio, and other material that is clearly identified for your use (“Assets”).  The Assets are protected by state, national, and international copyright, trademark, and other intellectual property laws.  Nevertheless, We (and Our licensors) grant to you the limited, non-exclusive, right and license to use the Assets solely as described on the Website, as limited by this Agreement, and provided further that you keep intact any and all copyright and other proprietary notices.</p>
<p class="MsoNormal">I.     The Website also contains other graphics, text, photographs, images, video, audio, software, code, and other material that is provided by Zambooki or its licensors and is not clearly identified as, or intended, for your use, including without limitation the organization, design, compilation, and “look and feel” of the Website, and advertising thereon (“Website Content”).  The Website Content is protected by state, national, and international copyright, trademark, and other intellectual property laws, and is the property of Zambooki or its licensors.  The copying, reproduction, publication, display, rearrangement, redistribution, modification, revision, alteration, cropping, re-sizing, reverse engineering, movement, removal, deletion, or other use or change by you, directly or indirectly, of any such Website Content, including but not limited to the removal or alteration of advertising, is strictly prohibited.</p>
<p class="MsoNormal">J.     You may not in any way make commercial or other unauthorized use, by publication, re‑transmission, distribution, performance, caching, or otherwise, of material obtained through the Website, including without limitation the Assets or Website Content, except as permitted by the Copyright Act or other law or as expressly permitted in writing by this Agreement, Zambooki, or the Website.</p>
<p class="MsoNormal">K.    You agree not to disrupt, overwhelm, attack, modify, reverse engineer, or interfere with the Website or its associated software, hardware, and/or servers in any way, and you agree not to impede or interfere with other Users’ use of the Website.</p>
<p class="MsoNormal">L.    Other than connecting to Zambooki’s servers by http requests using a Web browser, you may not attempt to gain access to Zambooki’s servers by any means - including, without limitation, by using administrator passwords or by masquerading as an administrator while using the Website or otherwise.</p>
<p class="MsoNormal">M.   You acknowledge that Zambooki has not reviewed and does not endorse the content of any sites linked to or from this Website and is not responsible for the content or actions of any other sites linked to or from this Website.  Your linking to any service or site is at your sole risk.</p>
<p class="MsoNormal">N.   You must provide and are solely responsible for all hardware and/or software necessary to access the Website.  You assume the entire cost of and responsibility for any damage to, and all necessary maintenance, repair, or correction of, that hardware and/or software.  The Website is provided for informational purposes only.  You expressly assume all risk for such use.</p>
<p class="MsoNormal">O.    You agree to provide true, accurate, current, and complete information about yourself as prompted by the Website.  If Zambooki has reasonable grounds to suspect that such information is untrue, inaccurate, or incomplete, We have the right to suspend or terminate your account and refuse any and all current or future use of the Website (or any portion thereof). </p>
<p class="MsoNormal">COMMENTS BY OTHERS ARE NOT ENDORSED BY ZAMBOOKI</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">Zambooki does not necessarily endorse, support, sanction, encourage, verify, or agree with the comments, opinions, or statements posted on forums, chats, or otherwise contained in the Website.  Any information or material placed online, including advice and opinions, are the views and responsibility of those who post the statements and do not necessarily represent the views of Zambooki or its third party service providers.  You agree that Zambooki and its third party service providers are not responsible, and shall have no liability to you, with respect to any information or materials posted by others, including defamatory, offensive, or illicit material, even material that violates this Agreement.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">USE OF MATERIAL SUPPLIED BY YOU</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">For information regarding use of information about you that you may supply or communicate to the Website, please see Our Privacy Policy.  Except as expressly provided otherwise in the Privacy Policy or in this Agreement, you agree that by posting messages, uploading text, graphics, photographs, images, video, or audio files, inputting data, or engaging in any other form of communication with or through the Website, you grant us a royalty-free, perpetual, non-exclusive, unrestricted, worldwide license to use, reproduce, modify, adapt, translate, enhance, transmit, distribute, publicly perform, display, or sublicense any such communication (including your identity and information about you) in any medium (now in existence or hereinafter developed) and for any purpose, including commercial purposes, and to authorize others to do so.  In addition, please be aware that information you disclose in publicly accessible portions of the Website will be available to all users of the Website, so you should be mindful of personal information and other content you may wish to post.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">COPYRIGHT COMPLAINTS</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">A.    Zambooki respects the intellectual property of others, and We ask Our Users to do the same.  Zambooki may, in appropriate circumstances and at its sole discretion, suspend or terminate the access of and take other action against Users who infringe the copyright rights of others.</p>
<p class="MsoNormal">B.    If you believe that your work has been copied and is accessible on the Website in a way that constitutes copyright infringement, or that the Website contains links or other references to another online location that contains material or activity that infringes your copyright rights, you may notify Zambooki by providing the following information (as required by the Online Copyright Infringement Liability Limitation Act of the Digital Millennium Copyright Act, 17 U.S.C. sec. 512) to Zambooki, LLC, ATTN: Heath, P.O. Box 71116, Tuscaloosa, Alabama 35407:</p>
<p class="MsoNormal">i.      A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</p>
<p class="MsoNormal">ii.    Identification of the copyrighted work claimed to have been infringed, or if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;</p>
<p class="MsoNormal">iii.   Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit Zambooki to locate the material;</p>
<p class="MsoNormal">iv.   Information reasonably sufficient to permit Zambooki to contact the complaining party, such as an address, telephone number, and if available, an electronic mail address at which the complaining party may be contacted;</p>
<p class="MsoNormal">v.     A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p>
<p class="MsoNormal">vi.   A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed</p>
<p class="MsoNormal">For communications on other matters, please contact Zambooki as described on the Website, or click here to e-mail.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">MERCHANDISE OR SERVICES SOLD ON OR THROUGH THE WEBSITE</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">Zambooki does not make any warranties with respect to any of the merchandise, products, and/or services featured, mentioned, or sold on or through the Website.  Transactions for any such item shall be between the User and the third party Contractor, without any involvement of Zambooki.  You agree that Zambooki is not responsible, and shall have no liability to you, with respect to merchandise, products, and/or services featured, mentioned, sold, or distributed on or through the Website, including illegal, offensive, or illicit, even items that violate this Agreement.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">INDEMNIFICATION</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">You agree to indemnify Zambooki and its affiliates, officers, owners, employees, agents, and representatives, and to defend and hold each of them harmless, from any and all claims and liabilities (including attorneys’ fees) which may arise from your submissions, from your unauthorized use of material obtained through the Website, or from your breach of this Agreement, or from any such acts through your use of the Website.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">EDITING AND DELETIONS</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">Zambooki reserves the right, but undertakes no duty, to review, edit, move, or delete any material provided for display or placed on the Website or its bulletin boards, in its sole discretion, without notice.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">ADDITIONAL RULES</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">Zambooki reserves the right to post, from time to time, additional rules of usage that apply to specific parts of the Website.  Such additional rules will be posted in the relevant parts of the Website.  Your continued use of the Website constitutes your agreement to comply with these additional rules.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">DISCLAIMER OF WARRANTY AND LIMITATION OF LIABILITY:</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">YOU ACKNOWLEDGE THAT YOU ARE USING THE WEBSITE AT YOUR OWN RISK.  THE WEBSITE IS PROVIDED “AS IS”, AND ZAMBOOKI, ITS AFFILIATES, OWNERS, OFFICERS, EMPLOYEES, AGENTS, AND REPRESENTATIVES HEREBY EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES, EXPRESS AND IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF ACCURACY, RELIABILITY, TITLE, MERCHANTABILITY, NON-INFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE OR ANY OTHER WARRANTY, CONDITION, GUARANTEE, OR REPRESENTATION, WHETHER ORAL, IN WRITING, OR IN ELECTRONIC FORM, INCLUDING, BUT NOT LIMITED TO, THE ACCURACY OR COMPLETENESS OF ANY INFORMATION CONTAINED THEREIN OR PROVIDED BY THE WEBSITE.  ZAMBOOKI, ITS AFFILIATES, OWNERS, OFFICERS, EMPLOYEES, AGENTS, AND REPRESENTATIVES DO NOT REPRESENT OR WARRANT THAT ACCESS TO THE WEBSITE WILL BE UNINTERRUPTED OR THAT THERE WILL BE NO FAILURES, ERRORS, OR OMISSIONS OR LOSS OF TRANSMITTED INFORMATION, OR THAT NO VIRUSES WILL BE TRANSMITTED ON OR THROUGH THE WEBSITE.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">ZAMBOOKI, ITS AFFILIATES AND ITS OWNERS, OFFICERS, EMPLOYEES, AGENTS, AND REPRESENTATIVES SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTIES FOR ANY DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ALLEGEDLY SUSTAINED ARISING OUT OF THIS AGREEMENT, THE PROVIDING OF THE WEBSITE HEREUNDER, THE SALE OR PURCHASE OF ANY SERVICES, GOODS, OR MERCHANDISE, YOUR ACCESS TO OR INABILITY TO ACCESS THE WEBSITE, INCLUDING FOR VIRUSES ALLEGED TO HAVE BEEN OBTAINED FROM THE WEBSITE, YOUR USE OF OR RELIANCE ON THE WEBSITE OR ANY OF THE MERCHANDISE, INFORMATION, OR MATERIALS AVAILABLE ON OR THROUGH THE WEBSITE, REGARDLESS OF THE TYPE OF CLAIM OR THE NATURE OF THE CAUSE OF ACTION, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  SOME STATES DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU.  YOU MAY ALSO HAVE OTHER RIGHTS THAT VARY FROM STATE TO STATE.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">YOU HEREBY AGREE TO RELEASE ZAMBOOKI, ITS AFFILIATES, AND EACH OF THEIR RESPECTIVE OWNERS, OFFICERS, EMPLOYEES, AGENTS, AND REPRESENTTIVES FROM CLAIMS, DEMANDS, AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, SUSPECTED AND UNSUSPECTED, DISCLOSED AND UNDISCLOSED (COLLECTIVELY, “CLAIMS”), ARISING OUT OF OR IN ANY WAY CONNECTED WITH YOUR USE OF THE WEBSITE.  IF YOU ARE A CALIFORNIA RESIDENT, YOU WAIVE CALIFORNIA CIVIL CODE SECTION 1542, WHICH STATES, IN PART: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR”.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">TERMINATION OR SUSPENSION OF ACCESS TO THE WEBSITE</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">Zambooki has the right to terminate and/or suspend your ability to access the Website or any portion thereof, for any or no reason, without notice.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">NO REPRESENTATIONS </p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">Zambooki makes no representation that materials on the Website are appropriate, available, or legal in any particular location.  Those who choose to access the Website do so on their own initiative and are responsible for compliance with local laws, if and to the extent local laws are applicable.</p>
<p class="MsoNormal"><span style="line-height: 1.3em;"> </span></p>
<p class="MsoNormal"><span style="line-height: 1.3em;">JURISDICTION</span></p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">You agree that this Agreement, for all purposes, shall be governed and construed in accordance with the laws of the State of Alabama applicable to contracts to be wholly performed therein, and any action based on, relating to, or alleging a breach of this Agreement must be brought in a state or federal court in Tuscaloosa, Alabama.  In addition, you agree to submit to the exclusive personal jurisdiction and venue of such courts.</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">IF YOU DO NOT AGREE TO ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT, YOU MUST NOT USE THE WEBSITE.  BY USING THE WEBSITE, YOU ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTOOD THE TERMS AND CONDITIONS OF THIS AGREEMENT AND YOU AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS.</p>';
	public $enable_hour = '0';
	public $admin_approval = '0';
	public $enable_acl = '1';
	public $map_in_auction_details = '1';
	public $enable_antispam_bot = '1';
	public $profile_mode = 'component';
	public $theme = 'default';
	public $allow_messenger = '0';
	public $show_paypalemail = '1';
	public $allow_paypal = '0';
	public $cron_password = 'pass';
	public $googlemap_maptype = 'ROADMAP';
	public $enable_bid_attach = '1';
	public $bid_attach_compulsory = '0';
	public $allow_user_set_messenger_fields_visibility = '0';
	public $allow_sellers_edit = '1';
	public $allow_only_invited_users = '1';
	public $aucttype_invite_interface = 'both';
	public $enable_auctiontype_public = '1';
	public $enable_auctiontype_private = '0';
	public $enable_auctiontype_invite = '1';
	public $bid_accept_user_commision = '2';
}