
INSERT INTO `#__rbid_fields_assoc` VALUES ('1', 'name', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('2', 'surname', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('3', 'address', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('4', 'city', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('5', 'country', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('6', 'phone', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('7', 'paypalemail', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('8', 'activity_domains', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('9', 'about_me', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('10', 'googleMaps_x', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('11', 'googleMaps_y', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('12', 'YM', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('13', 'Hotmail', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('14', 'Skype', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('15', 'verified', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('18', 'powerseller', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('19', 'Linkedin', '');
INSERT INTO `#__rbid_fields_assoc` VALUES ('20', 'Facebook', '');



INSERT INTO `#__rbid_country` VALUES (4,'AFGHANISTAN','AF',1);
INSERT INTO `#__rbid_country` VALUES (5,'ALAND ISLANDS','AX',0);
INSERT INTO `#__rbid_country` VALUES (6,'ALBANIA','AL',1);
INSERT INTO `#__rbid_country` VALUES (7,'ALGERIA','DZ',0);
INSERT INTO `#__rbid_country` VALUES (8,'AMERICAN SAMOA','AS',0);
INSERT INTO `#__rbid_country` VALUES (9,'ANDORRA','AD',0);
INSERT INTO `#__rbid_country` VALUES (10,'ANGOLA','AO',0);
INSERT INTO `#__rbid_country` VALUES (11,'ANGUILLA','AI',0);
INSERT INTO `#__rbid_country` VALUES (12,'ANTARCTICA','AQ',0);
INSERT INTO `#__rbid_country` VALUES (13,'ANTIGUA AND BARBUDA','AG',0);
INSERT INTO `#__rbid_country` VALUES (14,'ARGENTINA','AR',0);
INSERT INTO `#__rbid_country` VALUES (15,'ARMENIA','AM',0);
INSERT INTO `#__rbid_country` VALUES (16,'ARUBA','AW',0);
INSERT INTO `#__rbid_country` VALUES (17,'AUSTRALIA','AU',1);
INSERT INTO `#__rbid_country` VALUES (18,'AUSTRIA','AT',1);
INSERT INTO `#__rbid_country` VALUES (19,'AZERBAIJAN','AZ',0);
INSERT INTO `#__rbid_country` VALUES (20,'BAHAMAS','BS',0);
INSERT INTO `#__rbid_country` VALUES (21,'BAHRAIN','BH',0);
INSERT INTO `#__rbid_country` VALUES (22,'BANGLADESH','BD',0);
INSERT INTO `#__rbid_country` VALUES (23,'BARBADOS','BB',0);
INSERT INTO `#__rbid_country` VALUES (24,'BELARUS','BY',0);
INSERT INTO `#__rbid_country` VALUES (25,'BELGIUM','BE',0);
INSERT INTO `#__rbid_country` VALUES (26,'BELIZE','BZ',0);
INSERT INTO `#__rbid_country` VALUES (27,'BENIN','BJ',0);
INSERT INTO `#__rbid_country` VALUES (28,'BERMUDA','BM',0);
INSERT INTO `#__rbid_country` VALUES (29,'BHUTAN','BT',0);
INSERT INTO `#__rbid_country` VALUES (30,'BOLIVIA','BO',0);
INSERT INTO `#__rbid_country` VALUES (31,'BOSNIA AND HERZEGOVINA','BA',0);
INSERT INTO `#__rbid_country` VALUES (32,'BOTSWANA','BW',0);
INSERT INTO `#__rbid_country` VALUES (33,'BOUVET ISLAND','BV',0);
INSERT INTO `#__rbid_country` VALUES (34,'BRAZIL','BR',0);
INSERT INTO `#__rbid_country` VALUES (35,'BRITISH INDIAN OCEAN TERRITORY','IO',0);
INSERT INTO `#__rbid_country` VALUES (36,'BRUNEI DARUSSALAM','BN',0);
INSERT INTO `#__rbid_country` VALUES (37,'BULGARIA','BG',0);
INSERT INTO `#__rbid_country` VALUES (38,'BURKINA FASO','BF',0);
INSERT INTO `#__rbid_country` VALUES (39,'BURUNDI','BI',0);
INSERT INTO `#__rbid_country` VALUES (40,'CAMBODIA','KH',0);
INSERT INTO `#__rbid_country` VALUES (41,'CAMEROON','CM',0);
INSERT INTO `#__rbid_country` VALUES (42,'CANADA','CA',0);
INSERT INTO `#__rbid_country` VALUES (43,'CAPE VERDE','CV',0);
INSERT INTO `#__rbid_country` VALUES (44,'CAYMAN ISLANDS','KY',0);
INSERT INTO `#__rbid_country` VALUES (45,'CENTRAL AFRICAN REPUBLIC','CF',0);
INSERT INTO `#__rbid_country` VALUES (46,'CHAD','TD',0);
INSERT INTO `#__rbid_country` VALUES (47,'CHILE','CL',0);
INSERT INTO `#__rbid_country` VALUES (48,'CHINA','CN',0);
INSERT INTO `#__rbid_country` VALUES (49,'CHRISTMAS ISLAND','CX',0);
INSERT INTO `#__rbid_country` VALUES (50,'COCOS (KEELING) ISLANDS','CC',0);
INSERT INTO `#__rbid_country` VALUES (51,'COLOMBIA','CO',0);
INSERT INTO `#__rbid_country` VALUES (52,'COMOROS','KM',0);
INSERT INTO `#__rbid_country` VALUES (53,'CONGO','CG',0);
INSERT INTO `#__rbid_country` VALUES (54,'CONGO,THE DEMOCRATIC REPUBLIC OF THE','CD',0);
INSERT INTO `#__rbid_country` VALUES (55,'COOK ISLANDS','CK',0);
INSERT INTO `#__rbid_country` VALUES (56,'COSTA RICA','CR',0);
INSERT INTO `#__rbid_country` VALUES (57,'CROATIA','HR',0);
INSERT INTO `#__rbid_country` VALUES (58,'CUBA','CU',0);
INSERT INTO `#__rbid_country` VALUES (59,'CYPRUS','CY',0);
INSERT INTO `#__rbid_country` VALUES (60,'CZECH REPUBLIC','CZ',0);
INSERT INTO `#__rbid_country` VALUES (61,'DENMARK','DK',0);
INSERT INTO `#__rbid_country` VALUES (62,'DJIBOUTI','DJ',0);
INSERT INTO `#__rbid_country` VALUES (63,'DOMINICA','DM',0);
INSERT INTO `#__rbid_country` VALUES (64,'DOMINICAN REPUBLIC','DO',0);
INSERT INTO `#__rbid_country` VALUES (65,'ECUADOR','EC',0);
INSERT INTO `#__rbid_country` VALUES (66,'EGYPT','EG',0);
INSERT INTO `#__rbid_country` VALUES (67,'EL SALVADOR','SV',0);
INSERT INTO `#__rbid_country` VALUES (68,'EQUATORIAL GUINEA','GQ',0);
INSERT INTO `#__rbid_country` VALUES (69,'ERITREA','ER',0);
INSERT INTO `#__rbid_country` VALUES (70,'ESTONIA','EE',0);
INSERT INTO `#__rbid_country` VALUES (71,'ETHIOPIA','ET',0);
INSERT INTO `#__rbid_country` VALUES (72,'FALKLAND ISLANDS (MALVINAS)','FK',0);
INSERT INTO `#__rbid_country` VALUES (73,'FAROE ISLANDS','FO',0);
INSERT INTO `#__rbid_country` VALUES (74,'FIJI','FJ',0);
INSERT INTO `#__rbid_country` VALUES (75,'FINLAND','FI',0);
INSERT INTO `#__rbid_country` VALUES (76,'FRANCE','FR',1);
INSERT INTO `#__rbid_country` VALUES (77,'FRENCH GUIANA','GF',1);
INSERT INTO `#__rbid_country` VALUES (78,'FRENCH POLYNESIA','PF',0);
INSERT INTO `#__rbid_country` VALUES (79,'FRENCH SOUTHERN TERRITORIES','TF',0);
INSERT INTO `#__rbid_country` VALUES (80,'GABON','GA',0);
INSERT INTO `#__rbid_country` VALUES (81,'GAMBIA','GM',0);
INSERT INTO `#__rbid_country` VALUES (82,'GEORGIA','GE',0);
INSERT INTO `#__rbid_country` VALUES (83,'GERMANY','DE',1);
INSERT INTO `#__rbid_country` VALUES (84,'GHANA','GH',0);
INSERT INTO `#__rbid_country` VALUES (85,'GIBRALTAR','GI',0);
INSERT INTO `#__rbid_country` VALUES (86,'GREECE','GR',0);
INSERT INTO `#__rbid_country` VALUES (87,'GREENLAND','GL',0);
INSERT INTO `#__rbid_country` VALUES (88,'GRENADA','GD',0);
INSERT INTO `#__rbid_country` VALUES (89,'GUADELOUPE','GP',0);
INSERT INTO `#__rbid_country` VALUES (90,'GUAM','GU',0);
INSERT INTO `#__rbid_country` VALUES (91,'GUATEMALA','GT',0);
INSERT INTO `#__rbid_country` VALUES (92,'GUERNSEY','GG',0);
INSERT INTO `#__rbid_country` VALUES (93,'GUINEA','GN',0);
INSERT INTO `#__rbid_country` VALUES (94,'GUINEA-BISSAU','GW',0);
INSERT INTO `#__rbid_country` VALUES (95,'GUYANA','GY',0);
INSERT INTO `#__rbid_country` VALUES (96,'HAITI','HT',0);
INSERT INTO `#__rbid_country` VALUES (97,'HEARD ISLAND AND MCDONALD ISLANDS','HM',0);
INSERT INTO `#__rbid_country` VALUES (98,'HONDURAS','HN',0);
INSERT INTO `#__rbid_country` VALUES (99,'HONG KONG','HK',0);
INSERT INTO `#__rbid_country` VALUES (100,'HUNGARY','HU',0);
INSERT INTO `#__rbid_country` VALUES (101,'ICELAND','IS',0);
INSERT INTO `#__rbid_country` VALUES (102,'INDIA','IN',0);
INSERT INTO `#__rbid_country` VALUES (103,'INDONESIA','ID',0);
INSERT INTO `#__rbid_country` VALUES (104,'IRAN, ISLAMIC REPUBLIC OF','IR',0);
INSERT INTO `#__rbid_country` VALUES (105,'IRAQ','IQ',0);
INSERT INTO `#__rbid_country` VALUES (106,'IRELAND','IE',0);
INSERT INTO `#__rbid_country` VALUES (107,'ISLE OF MAN','IM',0);
INSERT INTO `#__rbid_country` VALUES (108,'ISRAEL','IL',0);
INSERT INTO `#__rbid_country` VALUES (109,'ITALY','IT',0);
INSERT INTO `#__rbid_country` VALUES (110,'JAMAICA','JM',0);
INSERT INTO `#__rbid_country` VALUES (111,'JAPAN','JP',0);
INSERT INTO `#__rbid_country` VALUES (112,'JERSEY','JE',0);
INSERT INTO `#__rbid_country` VALUES (113,'JORDAN','JO',0);
INSERT INTO `#__rbid_country` VALUES (114,'KAZAKHSTAN','KZ',0);
INSERT INTO `#__rbid_country` VALUES (115,'KENYA','KE',0);
INSERT INTO `#__rbid_country` VALUES (116,'KIRIBATI','KI',0);
INSERT INTO `#__rbid_country` VALUES (117,'KOREA, REPUBLIC OF','KR',0);
INSERT INTO `#__rbid_country` VALUES (118,'KUWAIT','KW',0);
INSERT INTO `#__rbid_country` VALUES (119,'KYRGYZSTAN','KG',0);
INSERT INTO `#__rbid_country` VALUES (120,'LATVIA','LV',0);
INSERT INTO `#__rbid_country` VALUES (121,'LEBANON','LB',0);
INSERT INTO `#__rbid_country` VALUES (122,'LESOTHO','LS',0);
INSERT INTO `#__rbid_country` VALUES (123,'LIBERIA','LR',0);
INSERT INTO `#__rbid_country` VALUES (124,'LIBYAN ARAB JAMAHIRIYA','LY',0);
INSERT INTO `#__rbid_country` VALUES (125,'LIECHTENSTEIN','LI',0);
INSERT INTO `#__rbid_country` VALUES (126,'LITHUANIA','LT',0);
INSERT INTO `#__rbid_country` VALUES (127,'LUXEMBOURG','LU',0);
INSERT INTO `#__rbid_country` VALUES (128,'MACAO','MO',0);
INSERT INTO `#__rbid_country` VALUES (129,'MACEDONI, THE FORMER YUGOSLAV REPUBLIC OF','MK',0);
INSERT INTO `#__rbid_country` VALUES (130,'MADAGASCAR','MG',0);
INSERT INTO `#__rbid_country` VALUES (131,'MALAWI','MW',0);
INSERT INTO `#__rbid_country` VALUES (132,'MALAYSIA','MY',0);
INSERT INTO `#__rbid_country` VALUES (133,'MALDIVES','MV',0);
INSERT INTO `#__rbid_country` VALUES (134,'MALI','ML',0);
INSERT INTO `#__rbid_country` VALUES (135,'MALTA','MT',0);
INSERT INTO `#__rbid_country` VALUES (136,'MARSHALL ISLANDS','MH',0);
INSERT INTO `#__rbid_country` VALUES (137,'MARTINIQUE','MQ',0);
INSERT INTO `#__rbid_country` VALUES (138,'MAURITANIA','MR',0);
INSERT INTO `#__rbid_country` VALUES (139,'MAURITIUS','MU',0);
INSERT INTO `#__rbid_country` VALUES (140,'MAYOTTE','YT',0);
INSERT INTO `#__rbid_country` VALUES (141,'MEXICO','MX',0);
INSERT INTO `#__rbid_country` VALUES (142,'MICRONESIA, FEDERATED STATES OF','FM',0);
INSERT INTO `#__rbid_country` VALUES (143,'MOLDOVA, REPUBLIC OF','MD',0);
INSERT INTO `#__rbid_country` VALUES (144,'MONACO','MC',0);
INSERT INTO `#__rbid_country` VALUES (145,'MONGOLIA','MN',0);
INSERT INTO `#__rbid_country` VALUES (146,'MONTENEGRO','ME',0);
INSERT INTO `#__rbid_country` VALUES (147,'MONTSERRAT','MS',0);
INSERT INTO `#__rbid_country` VALUES (148,'MOROCCO','MA',0);
INSERT INTO `#__rbid_country` VALUES (149,'MOZAMBIQUE','MZ',0);
INSERT INTO `#__rbid_country` VALUES (150,'MYANMAR','MM',0);
INSERT INTO `#__rbid_country` VALUES (151,'NAMIBIA','NA',0);
INSERT INTO `#__rbid_country` VALUES (152,'NAURU','NR',0);
INSERT INTO `#__rbid_country` VALUES (153,'NEPAL','NP',0);
INSERT INTO `#__rbid_country` VALUES (154,'NETHERLANDS','NL',0);
INSERT INTO `#__rbid_country` VALUES (155,'NETHERLANDS ANTILLES','AN',0);
INSERT INTO `#__rbid_country` VALUES (156,'NEW CALEDONIA','NC',0);
INSERT INTO `#__rbid_country` VALUES (157,'NEW ZEALAND','NZ',0);
INSERT INTO `#__rbid_country` VALUES (158,'NICARAGUA','NI',0);
INSERT INTO `#__rbid_country` VALUES (159,'NIGER','NE',0);
INSERT INTO `#__rbid_country` VALUES (160,'NIGERIA','NG',0);
INSERT INTO `#__rbid_country` VALUES (161,'NIUE','NU',0);
INSERT INTO `#__rbid_country` VALUES (162,'NORFOLK ISLAND','NF',0);
INSERT INTO `#__rbid_country` VALUES (163,'NORTHERN MARIANA ISLANDS','MP',0);
INSERT INTO `#__rbid_country` VALUES (164,'NORWAY','NO',0);
INSERT INTO `#__rbid_country` VALUES (165,'OMAN','OM',0);
INSERT INTO `#__rbid_country` VALUES (166,'PAKISTAN','PK',0);
INSERT INTO `#__rbid_country` VALUES (167,'PALAU','PW',0);
INSERT INTO `#__rbid_country` VALUES (168,'PALESTINIAN TERRITORY, OCCUPIED','PS',0);
INSERT INTO `#__rbid_country` VALUES (169,'PANAMA','PA',0);
INSERT INTO `#__rbid_country` VALUES (170,'PAPUA NEW GUINEA','PG',0);
INSERT INTO `#__rbid_country` VALUES (171,'PARAGUAY','PY',0);
INSERT INTO `#__rbid_country` VALUES (172,'PERU','PE',0);
INSERT INTO `#__rbid_country` VALUES (173,'PHILIPPINES','PH',0);
INSERT INTO `#__rbid_country` VALUES (174,'PITCAIRN','PN',0);
INSERT INTO `#__rbid_country` VALUES (175,'POLAND','PL',0);
INSERT INTO `#__rbid_country` VALUES (176,'PORTUGAL','PT',0);
INSERT INTO `#__rbid_country` VALUES (177,'PUERTO RICO','PR',0);
INSERT INTO `#__rbid_country` VALUES (178,'QATAR','QA',0);
INSERT INTO `#__rbid_country` VALUES (179,'R�UNION','RE',0);
INSERT INTO `#__rbid_country` VALUES (180,'ROMANIA','RO',1);
INSERT INTO `#__rbid_country` VALUES (181,'RUSSIAN FEDERATION','RU',0);
INSERT INTO `#__rbid_country` VALUES (182,'RWANDA','RW',0);
INSERT INTO `#__rbid_country` VALUES (183,'SAINT HELENA','SH',0);
INSERT INTO `#__rbid_country` VALUES (184,'SAINT KITTS AND NEVIS','KN',0);
INSERT INTO `#__rbid_country` VALUES (185,'SAINT LUCIA','LC',0);
INSERT INTO `#__rbid_country` VALUES (186,'SAINT PIERRE AND MIQUELON','PM',0);
INSERT INTO `#__rbid_country` VALUES (187,'SAINT VINCENT AND THE GRENADINES','VC',0);
INSERT INTO `#__rbid_country` VALUES (188,'SAMOA','WS',0);
INSERT INTO `#__rbid_country` VALUES (189,'SAN MARINO','SM',0);
INSERT INTO `#__rbid_country` VALUES (190,'SAO TOME AND PRINCIPE','ST',0);
INSERT INTO `#__rbid_country` VALUES (191,'SAUDI ARABIA','SA',0);
INSERT INTO `#__rbid_country` VALUES (192,'SENEGAL','SN',0);
INSERT INTO `#__rbid_country` VALUES (193,'SERBIA','RS',0);
INSERT INTO `#__rbid_country` VALUES (194,'SEYCHELLES','SC',0);
INSERT INTO `#__rbid_country` VALUES (195,'SIERRA LEONE','SL',0);
INSERT INTO `#__rbid_country` VALUES (196,'SINGAPORE','SG',0);
INSERT INTO `#__rbid_country` VALUES (197,'SLOVAKIA','SK',0);
INSERT INTO `#__rbid_country` VALUES (198,'SLOVENIA','SI',0);
INSERT INTO `#__rbid_country` VALUES (199,'SOLOMON ISLANDS','SB',0);
INSERT INTO `#__rbid_country` VALUES (200,'SOMALIA','SO',0);
INSERT INTO `#__rbid_country` VALUES (201,'SOUTH AFRICA','ZA',0);
INSERT INTO `#__rbid_country` VALUES (202,'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','GS',0);
INSERT INTO `#__rbid_country` VALUES (203,'SPAIN','ES',0);
INSERT INTO `#__rbid_country` VALUES (204,'SRI LANKA','LK',0);
INSERT INTO `#__rbid_country` VALUES (205,'SUDAN','SD',0);
INSERT INTO `#__rbid_country` VALUES (206,'SURINAME','SR',0);
INSERT INTO `#__rbid_country` VALUES (207,'SVALBARD AND JAN MAYEN','SJ',0);
INSERT INTO `#__rbid_country` VALUES (208,'SWAZILAND','SZ',0);
INSERT INTO `#__rbid_country` VALUES (209,'SWEDEN','SE',0);
INSERT INTO `#__rbid_country` VALUES (210,'SWITZERLAND','CH',1);
INSERT INTO `#__rbid_country` VALUES (211,'SYRIAN ARAB REPUBLIC','SY',0);
INSERT INTO `#__rbid_country` VALUES (212,'TAIWAN, PROVINCE OF CHINA','TW',0);
INSERT INTO `#__rbid_country` VALUES (213,'TAJIKISTAN','TJ',0);
INSERT INTO `#__rbid_country` VALUES (214,'TANZANIA, UNITED REPUBLIC OF','TZ',0);
INSERT INTO `#__rbid_country` VALUES (215,'THAILAND','TH',0);
INSERT INTO `#__rbid_country` VALUES (216,'TIMOR-LESTE','TL',0);
INSERT INTO `#__rbid_country` VALUES (217,'TOGO','TG',0);
INSERT INTO `#__rbid_country` VALUES (218,'TOKELAU','TK',0);
INSERT INTO `#__rbid_country` VALUES (219,'TONGA','TO',0);
INSERT INTO `#__rbid_country` VALUES (220,'TRINIDAD AND TOBAGO','TT',0);
INSERT INTO `#__rbid_country` VALUES (221,'TUNISIA','TN',0);
INSERT INTO `#__rbid_country` VALUES (222,'TURKEY','TR',0);
INSERT INTO `#__rbid_country` VALUES (223,'TURKMENISTAN','TM',0);
INSERT INTO `#__rbid_country` VALUES (224,'TURKS AND CAICOS ISLANDS','TC',0);
INSERT INTO `#__rbid_country` VALUES (225,'TUVALU','TV',0);
INSERT INTO `#__rbid_country` VALUES (226,'UGANDA','UG',0);
INSERT INTO `#__rbid_country` VALUES (227,'UKRAINE','UA',0);
INSERT INTO `#__rbid_country` VALUES (228,'UNITED ARAB EMIRATES','AE',0);
INSERT INTO `#__rbid_country` VALUES (229,'UNITED KINGDOM','GB',1);
INSERT INTO `#__rbid_country` VALUES (230,'UNITED STATES','US',1);
INSERT INTO `#__rbid_country` VALUES (231,'UNITED STATES MINOR OUTLYING ISLANDS','UM',0);
INSERT INTO `#__rbid_country` VALUES (232,'URUGUAY','UY',0);
INSERT INTO `#__rbid_country` VALUES (233,'UZBEKISTAN','UZ',0);
INSERT INTO `#__rbid_country` VALUES (234,'VANUATU','VU',0);
INSERT INTO `#__rbid_country` VALUES (235,'VATICAN CITY STATE (HOLY SEE)','VA',0);
INSERT INTO `#__rbid_country` VALUES (236,'VENEZUELA','VE',0);
INSERT INTO `#__rbid_country` VALUES (237,'VIET NAM','VN',0);
INSERT INTO `#__rbid_country` VALUES (238,'VIRGIN ISLANDS, BRITISH','VG',0);
INSERT INTO `#__rbid_country` VALUES (239,'VIRGIN ISLANDS, U.S.','VI',0);
INSERT INTO `#__rbid_country` VALUES (240,'WALLIS AND FUTUNA','WF',0);
INSERT INTO `#__rbid_country` VALUES (241,'WESTERN SAHARA','EH',0);
INSERT INTO `#__rbid_country` VALUES (242,'YEMEN','YE',0);
INSERT INTO `#__rbid_country` VALUES (243,'ZAMBIA','ZM',0);
INSERT INTO `#__rbid_country` VALUES (244,'ZIMBABWE','ZW',0);


INSERT INTO `#__rbid_currency` VALUES ('1', 'USD', '4', '0.93406',  '1');
INSERT INTO `#__rbid_currency` VALUES ('2', 'EUR', '5', '1.23669', null);
INSERT INTO `#__rbid_currency` VALUES ('5', 'CHF', '2', '1.02250', null);
INSERT INTO `#__rbid_currency` VALUES ('8', 'AUD', '3', '1.00000', null);


INSERT INTO `#__rbid_mails` VALUES (2,'new_message','Dear %NAME%  %SURNAME%,  You received a new reply to your bid regarding the Auction:  %AUCTIONTITLE%  You can see the message here  %AUCTIONLINK%  You must login to read the message.','New message regarding Auction %AUCTIONTITLE%',0);
INSERT INTO `#__rbid_mails` VALUES (3,'new_bid','Dear %NAME% %SURNAME%,  You received a new Bid for your auction %AUCTIONTITLE%  You can get more details on the webpage  %AUCTIONLINK%','New bid on your Auction %AUCTIONTITLE%',0);
INSERT INTO `#__rbid_mails` VALUES (4,'bid_accepted','Dear %NAME% %SURNAME%,  Your Bid for the auction %AUCTIONTITLE% won!  Congratulations!!  You can get more details on the webpage  %AUCTIONLINK%','Your Bid was accepted',0);
INSERT INTO `#__rbid_mails` VALUES (5,'bid_lost','Dear %NAME% %SURNAME%,  Unfortunately, your Bid for the auction %AUCTIONTITLE% has lost  You can get more details on the webpage  %AUCTIONLINK%','Informations about your bid on %AUCTIONTITLE%',0);
INSERT INTO `#__rbid_mails` VALUES (6,'bid_bid_canceled','One bid was cancelled','One bid was canceled',0);
INSERT INTO `#__rbid_mails` VALUES (7,'bid_watchlist_canceled','Dear %NAME% %SURNAME%,  The auction %AUCTIONTITLE% from your watchlist was canceled!  You can get more details on the webpage  %AUCTIONLINK%','Informations about your Watched Auction  %AUCTIONTITLE%',0);
INSERT INTO `#__rbid_mails` VALUES (8,'bid_canceled','Dear %NAME% %SURNAME%,  The auction %AUCTIONTITLE%  was canceled!  You can get more details on the webpage  %AUCTIONLINK%','Informations about your bid on  %AUCTIONTITLE%',0);
INSERT INTO `#__rbid_mails` VALUES (9,'bid_watchlist_closed','Dear %NAME% %SURNAME%,  The auction %AUCTIONTITLE% from your watchlist was closed !  You can get more details on the webpage  %AUCTIONLINK%','Informations about your Watched Auction %AUCTIONTITLE%',0);
INSERT INTO `#__rbid_mails` VALUES (10,'bid_closed','Dear %NAME% %SURNAME%,  The auction %AUCTIONTITLE% was closed !  You can get more details on the webpage  %AUCTIONLINK%','Informations about your bid on %AUCTIONTITLE%',0);
INSERT INTO `#__rbid_mails` VALUES (11,'bid_rate','Dear %NAME% %SURNAME%,  You received a rating for the auction %AUCTIONTITLE%  !  You can get more details on the webpage  %AUCTIONLINK%','New Rating received',0);
INSERT INTO `#__rbid_mails` VALUES (12,'bid_admin_message','Dear %NAME% %SURNAME%,  You received a message from one of the Administrators regarding your auction %AUCTIONTITLE%!  You can get more details on the webpage  %AUCTIONLINK%','New Message from an Admin regarding %AUCTIONTITLE%',0);
INSERT INTO `#__rbid_mails` VALUES (13,'bid_your_will_expire','Dear %NAME% %SURNAME%,  Your Auction %AUCTIONTITLE% will soon expire !  You can get more details on the webpage  %AUCTIONLINK%','Your Auction %AUCTIONTITLE% will soon expire',0);
INSERT INTO `#__rbid_mails` VALUES (14,'bid_watchlist_will_expire','Dear %NAME% %SURNAME%,  The Auction you watched: %AUCTIONTITLE% will soon expire !  You can get more details on the webpage  %AUCTIONLINK%','Informations about your watched Auction  %AUCTIONTITLE%',0);
INSERT INTO `#__rbid_mails` VALUES (15,'new_auction_watch','Dear %NAME% %SURNAME%,  There is a new Auction in the category you watched: %AUCTIONTITLE%  You can get more details on the webpage  %AUCTIONLINK%','Informations about your watched Category  %CATTITLE%',0);
INSERT INTO `#__rbid_mails` VALUES (16,'new_auction_created','Dear %NAME% %SURNAME%,  Your Auction has been created successfully: %AUCTIONTITLE%  You can get more details on the webpage  %AUCTIONLINK%','Your Auction: %AUCTIONTITLE% has been created successfully',0);
INSERT INTO `#__rbid_mails` VALUES (17,'bid_admin_close_auction','Dear %NAME% %SURNAME%,  Your Auction has been closed by admin - %AUCTIONTITLE%  You can get more details on the webpage  %AUCTIONLINK%','Your Auction: %AUCTIONTITLE% has been closed by Admin',0);
INSERT INTO `#__rbid_mails` VALUES (18,'bid_admin_approval','Dear %NAME% %SURNAME%,  A new auction was placed  - %AUCTIONTITLE%  and it needs Admin Approval.','A new auction has been placed: %AUCTIONTITLE%',0);
INSERT INTO `#__rbid_mails` VALUES (19,'bid_choose_winner','<p>You can get more details on the webpage  %AUCTIONLINK%</p><p>You can get more details on the webpage  %AUCTIONLINK%</p>','You need to choose a winner for your auction',0);
INSERT INTO `#__rbid_mails` VALUES (20, 'bid_new_invite','Dear %NAME% %SURNAME%,  You have an invitation for new auction - %AUCTIONTITLE% .','',0);
INSERT INTO `#__rbid_mails` VALUES (21, 'user_withdraw_funds', "Dear %NAME% %SURNAME%, \r\n\n Your request for withdrawal has been sent to an admin.", 'Your request for withdrawal has been sent', 0);
INSERT INTO `#__rbid_mails` VALUES (22, 'admin_pay_requested_withdraw', "<p>Dear %NAME% %SURNAME%, \r\n\n  You have a new request for withdraw funds.</p>", 'You have a new request for withdraw funds', 0);


INSERT INTO `#__rbid_paysystems` VALUES ('1', 'Paypal', 'pay_paypal', '1', 'paypalemail=\"change@me.com1\"\nuse_sandbox=\"1\"\nauto_accept=\"1\"', '1', '1');
INSERT INTO `#__rbid_paysystems` VALUES ('2', 'Moneybookers', 'pay_moneybookers', '1', 'email=\"change@me.com1\"', '2', '0');
INSERT INTO `#__rbid_paysystems` VALUES ('3', '2Checkout', 'pay_2checkout', '0', 'x_login=\"change@me.com2\"\ntest_mode=\"1\"', '3', '0');
INSERT INTO `#__rbid_paysystems` VALUES ('4', 'Bankwire', 'pay_banktransfer', '1', 'bank_info=\"<p><strong>Please wire the money to my bank account.</strong></p>\"', '4', '0');
INSERT INTO `#__rbid_paysystems` VALUES ('5', 'Sagepayments.net', 'pay_sagepayments', '0', 'Terminal_id=\"2131231\"\nLogo_url=\"\"\nB_color=\"\"\nBF_color=\"\"\nM_color=\"\"\nF_color=\"\"', '6', '0');


INSERT INTO `#__rbid_pricing` VALUES ('1', 'featured', 'fixed', 'Featured Auction', '33.00', 'USD', '0', 'price_powerseller=\"22\"\nprice_verified=\"11\"\ncategory_pricing_enabled=', '2');
INSERT INTO `#__rbid_pricing` VALUES ('2', 'listing', 'fixed', 'Pay per Listing', '10.00', 'USD', '0', 'price_powerseller=\"\"\nprice_verified=\"\"\ncategory_pricing_enabled=\nemail_text=\"Hello %SURNAME%,\nWe kindly remind you that you have an outstanding payment of %BALANCE% for the services provided by our site.\nLog in using your username \"%USERNAME%\" and follow this link in order to pay the fees:\n%LINK%\"', '1');
INSERT INTO `#__rbid_pricing` VALUES ('3', 'comission', 'percent', 'Earn Commission', '10.00', '', '1', 'price_powerseller=\"5\"\nprice_verified=\"1\"\ncategory_pricing_enabled=\nemail_text=\"PHA+SGVsbG8gJVNVUk5BTUUlLGE8L3A+DQo8cD7CoDwvcD4NCjxwPmFkIC0gJUJBTEFOQ0UlPC9wPg0KPHA+YXMgLSAlTElOSyU8L3A+DQo8cD5kYTwvcD4NCjxwPnNkPC9wPg0KPHA+YXM8L3A+\"', '2');
INSERT INTO `#__rbid_pricing` VALUES ('4', 'contact', 'fixed', 'Pay per Contact', '44.00', 'USD', '0', 'price_powerseller=\"4\"\nprice_verified=\"2\"\ncategory_pricing_enabled=', '2');
INSERT INTO `#__rbid_pricing` VALUES ('5', 'bid', 'fixed', 'Pay per Bid', '55.00', 'USD', '0', 'price_powerseller=\"5\"\nprice_verified=\"1\"\ncategory_pricing_enabled=', '2');

